let booksname = [
    ['Frankenstein','Mery Shelley'],
    ['Anna Karenina',' Leo Tolstoy'],
    ['Charltte Bronte', 'Jane Eyre'],
    ['Les Misarables','Victor Hugo'],
    ['Thérèse Raquin','Émile Zola'],
    ['The Sailor Who Fell from Grace with the Sea','Yukio Mishima'],
    ['The Red and The Black', 'Stendhal'],
    ['The Story of a Shipwrecked Sailor','Gabriel García Márquez'],
    ['The Vampire Lestat', ' Anne Rice'],
    ['Absalom, Absalom!','William Faulkner'],
    ['It Ends with Us: A Novel','Colleen Hoover'],
    ['Outlander','Diana Gabaldon'],
    ['The Proposal','Jasmine Guillory'],
    ['The Hating Game','Sally Thorne'],
    ['Vision in White','Nora Roberts'],
    ['Beautiful Disaster','Jamie Mcguir'],
    ['Gone with the Wind','Margaret Mitchell'],
    ['A Long Petal of the Sea','Isabel Allende'],
    ['Pride and Prejudice','Jane Austen'],
    ['The Thorn Birds','Colleen Mccullough'],
    ['1984','George Orwell'],
    ['The City & the City', 'China Miéville'],
    ['Altered Carbon','Richard Morgan'],
    ['Amatka','Karin Tidback'],
    ['Anmonite','Nikola Griffith'],
    ['The Best of all possible words','Karen Lord'],
    ['The Big Book of Science fiction',''],
    ['The Blazing World','Lady Margaret Lucas Cavendish'],
    ['A Canticle for Leibowitz','Walter M. Miller Jr.'],
    ['The children of Men','PD james'],
    ['Tom Clancys','Marc Cameron'],
    ['FatherLand','Robert Harris'],
    ['Black Sun','Owen Mathhews'],
    ['Origin','Dann Brown'],
    ['Jurasssic Park','Michael Crichton'],
    ['Red Rabbit','Tom Clancy'],
    ['The Da Vinci Code','Dan Brown'],
    ['The Martian','Andy Weir'],
    ['The 39 Steps','Vintage Bucon'],
    ['The Cretan Runner','George Psychoundakis'],
    ['India that is Bharata','J. Sai Deepak'],
    ['The Psychology of Money','Morgan Housel'],
    ['The Richest man in Babylon','George S. Clason'],
    ['An entierly new history','Francis Gautier'],
    ['Five Point Someone','Cheta Bhagat'],
    ['Half Girlfriend','Chetan Bhagat'],
    ['The 3 mistakes of my Life','Chetan Bhagat'],
    ['2 States','Chetan Bhagat'],
    ['The Guide','R. K. Narayan'],
    ['The great Indian Novel','S. Tharoor'],
    ['Train to Pakistan','Khushbant Singh'],
    ['The Suitable Boy','Vikram Seth']
]
export default booksname;